package lxy;

public enum DemoType {
    SELECT,
    AGGREGATION,
    FILTER,
    FILTER_AND_AGGREGATION,
    DATA_WINDOW,
    DATA_WINDOW_AND_AGGREGATION,
    FILTER_DATA_WINDOW_AND_AGGREGATION,
    WHERE,
    TIME_WINDOW_AGGREGATION,
    PARTITIONED_STATEMENT,
    OUTPUT_RATE_LIMIT,
    PARTITIONED_OUTPUT_RATE_LIMIT,
    NAMED_WINDOW,
    TABLE,
    AGG_TYPE_UNAGG_UNGRP,
    AGG_TYPE_FULL_AGG_UNGRP,
    AGG_TYPE_AGG_UNGRP,
    AGG_TYPE_FULL_AGG_GRP,
    AGG_TYPE_AGG_GRP,
    Match_Recognize_Patterns,
    EPL_PATTERN
}
